name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/forum-api-hapi
            git pull origin master
            if [ -f ~/.nvm/nvm.sh ]; then . ~/.nvm/nvm.sh; fi
            nvm use v14
            npm install
            npm run migrate up
            pm2 restart forum-api
